---
- name: Show PowerVC group details (primary site)
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Show group details
      ibm.powervc.group_action:
        cloud: "CLOUDNAME"
        id: "12345678-aaaa-bbbb-cccc-123456789abc"
        action: show
        validate_certs: no


- name: Show PowerVC group details (secondary site)
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Show group details on secondary
      ibm.powervc.group_action:
        cloud: "CLOUDNAME"
        id: "12345678-aaaa-bbbb-cccc-123456789abc"
        action: show
        secondary: true
        validate_certs: no


- name: Show PowerVC group relationship (primary site)
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Show group relationship
      ibm.powervc.group_action:
        cloud: "CLOUDNAME"
        id: "12345678-aaaa-bbbb-cccc-123456789abc"
        action: relationship
        validate_certs: no


- name: Show PowerVC group relationship (secondary site)
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Show group relationship on secondary
      ibm.powervc.group_action:
        cloud: "CLOUDNAME"
        id: "12345678-aaaa-bbbb-cccc-123456789abc"
        action: relationship
        secondary: true
        validate_certs: no


- name: Start PowerVC group (master as primary)
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Start group with master as primary
      ibm.powervc.group_action:
        cloud: "CLOUDNAME"
        id: "12345678-aaaa-bbbb-cccc-123456789abc"
        action: start
        primary: master
        validate_certs: no


- name: Start PowerVC group (aux as primary)
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Start group with auxiliary as primary
      ibm.powervc.group_action:
        cloud: "CLOUDNAME"
        id: "12345678-aaaa-bbbb-cccc-123456789abc"
        action: start
        primary: aux
        validate_certs: no


- name: Stop PowerVC group (access disabled)
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Stop group with access disabled
      ibm.powervc.group_action:
        cloud: "CLOUDNAME"
        id: "12345678-aaaa-bbbb-cccc-123456789abc"
        action: stop
        access: false
        validate_certs: no


- name: Stop PowerVC group (access enabled)
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Stop group with access enabled
      ibm.powervc.group_action:
        cloud: "CLOUDNAME"
        id: "12345678-aaaa-bbbb-cccc-123456789abc"
        action: stop
        access: true
        validate_certs: no

