---
- name: Volume Update Playbook
  hosts: localhost
  gather_facts: no
  vars:
   auth:
    auth_url: https://<POWERVC>:5000/v3
    project_name: PROJECT-NAME
    username: USERID
    password: PASSWORD
    project_domain_name: PROJECT_DOMAIN_NAME
    user_domain_name: USER_DOMAIN_NAME
  tasks:
     - name: Perform Volume Update Operations
       ibm.powervc.volume_update:
          auth: "{{ auth }}"
          name: "VOLUME_NAME"
<<<<<<< HEAD
          size: "SIZE"
=======
>>>>>>> d7185f3 (Add Volume Info, VolumeType Info and Volume Update features)
          validate_certs: no
       register: result
     - debug:
          var: result

- name: Volume Update Playbook
  hosts: localhost
  gather_facts: no
  tasks:
     - name: Perform Volume Update Operations
       ibm.powervc.volume_update:
          cloud: "CLOUD_NAME"
          name: "VOLUME_NAME"
<<<<<<< HEAD
          enable_sharing_vm: "ENABLE_SHARING_VM"
=======
>>>>>>> d7185f3 (Add Volume Info, VolumeType Info and Volume Update features)
          validate_certs: no
       register: result
     - debug:
          var: result

- name: Volume Update Playbook using the Volume IDs
  hosts: localhost
  gather_facts: no
  tasks:
     - name: Perform Volume Update Operations
       ibm.powervc.volume_update:
          cloud: "CLOUD_NAME"
          id: "VOLUME_ID"
<<<<<<< HEAD
          size: "SIZE"
=======
>>>>>>> d7185f3 (Add Volume Info, VolumeType Info and Volume Update features)
          validate_certs: no
       register: result
     - debug:
          var: result