---
- name: List all the volume type details
  hosts: localhost
  gather_facts: no
  tasks:
     - name: Fetch Volume Type Details
       ibm.powervc.volume_type_info:
          cloud: "CLOUD_NAME"
          validate_certs: no
       register: result
     - debug:
          var: result

- name: List Volume Type Details Playbook using ID
  hosts: localhost
  gather_facts: no
  tasks:
     - name: Fetch Volume Type Details
       ibm.powervc.volume_type_info:
          cloud: "CLOUD_NAME"
          id: "VOLUME_ID"
          validate_certs: no
       register: result
     - debug:
          var: result

- name: List Volume Type Details Playbook using Name
  hosts: localhost
  gather_facts: no
  tasks:
     - name: Fetch Volume Type Details
       ibm.powervc.volume_type_info:
          cloud: "CLOUD_NAME"
          name: "VOLUME_NAME"
          validate_certs: no
       register: result
     - debug:
          var: result